"""empty message

Revision ID: 6e20ec5335c6
Revises: 3937b99296e3
Create Date: 2022-03-09 20:03:19.774997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e20ec5335c6'
down_revision = '3937b99296e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('rank', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rank')
    # ### end Alembic commands ###
